"use client"; // Это указание для использования компонента на стороне клиента в Next.js

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCoffee,
  faUser,
  faHome,
  faCar,
  faShoppingCart,
  faUtensils,
  faDollarSign,
  faWallet,
  faBook,
  faBriefcase,
  faHeart,
  faPlane,
  faGlobe,
  faMobileAlt,
  faLaptop,
  faBell,
  faMusic,
  faFilm,
  faGamepad,
  faTree,
  faMountain,
  faBicycle,
  faBasketballBall,
  faTools,
  faLightbulb,
  faCalendarAlt,
  faCamera,
  faTshirt,
  faBaby,
  faDog,
  faGraduationCap,
  faMapMarkerAlt,
  faShieldAlt,
  faRocket,
  faHandshake,
  faChartLine,
  faStar,
  faThumbsUp,
  faBuilding,
  faTreeCity,
  faGift,
  faClipboard,
  faPaw,
  faPhone,
  faMedkit,
  faAnchor,
  faWrench,
  faCogs,
  faBullhorn,
  faKey,
  faGlasses,
  faClipboardCheck,
  faStethoscope,
  faMap,
  faCode,
  faWifi,
  faTruck,
  faChartPie,
  faSnowflake,
  faMagic,
  faEnvelope,
  faSuitcaseMedical
} from "@fortawesome/free-solid-svg-icons";

const iconMap = {
  coffee: faCoffee,
  user: faUser,
  home: faHome,
  car: faCar,
  shoppingCart: faShoppingCart,
  utensils: faUtensils,
  dollarSign: faDollarSign,
  wallet: faWallet,
  book: faBook,
  briefcase: faBriefcase,
  heart: faHeart,
  plane: faPlane,
  globe: faGlobe,
  mobileAlt: faMobileAlt,
  laptop: faLaptop,
  bell: faBell,
  music: faMusic,
  film: faFilm,
  gamepad: faGamepad,
  tree: faTree,
  mountain: faMountain,
  bicycle: faBicycle,
  basketballBall: faBasketballBall,
  tools: faTools,
  lightbulb: faLightbulb,
  calendarAlt: faCalendarAlt,
  camera: faCamera,
  tshirt: faTshirt,
  baby: faBaby,
  dog: faDog,
  graduationCap: faGraduationCap,
  mapMarkerAlt: faMapMarkerAlt,
  shieldAlt: faShieldAlt,
  rocket: faRocket,
  handshake: faHandshake,
  chartLine: faChartLine,
  star: faStar,
  thumbsUp: faThumbsUp,
  building: faBuilding,
  treeCity: faTreeCity,
  gift: faGift,
  clipboard: faClipboard,
  paw: faPaw,
  phone: faPhone,
  medkit: faMedkit,
  anchor: faAnchor,
  wrench: faWrench,
  cogs: faCogs,
  bullhorn: faBullhorn,
  key: faKey,
  glasses: faGlasses,
  clipboardCheck: faClipboardCheck,
  stethoscope: faStethoscope,
  map: faMap,
  code: faCode,
  wifi: faWifi,
  truck: faTruck,
  chartPie: faChartPie,
  snowflake: faSnowflake,
  magic: faMagic,
  envelope: faEnvelope,
  "suitcase-medical": faSuitcaseMedical,
};
const IconMapper = ({ iconClass, iconColor }) => {
  const icon = iconMap[iconClass];

  if (!icon) {
    console.warn(`Icon "${iconClass}" not found in iconMap.`);
    return null; // Если иконка не найдена, возвращаем null
  }

  return (
    <FontAwesomeIcon
      icon={icon}
      style={{ color: iconColor, fontSize: "24px" }}
    />
  );
};

export default IconMapper;
