// app/layout.js
import "./globals.css";
import Providers from "./components/Providers";
import MainLayout from "./components/MainLayout/MainLayout"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
